services:
  - type: web
    name: fertilizer-recommendation
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        value: sqlite:///fertilizer.db
      - key: JWT_SECRET
        value: "Sagar@123"
